Infex #461 Update opensearch instance type in AWS examples
camunda/camunda-tf-eks-module pull request #197
Opened 2024-12-17 17:51 UTC by bkenez

As defined in [https://github.com/camunda/team-infrastructure-experience/issues/461](this ticket) the instance type of AWS opensearch examples has been modified from t3.medium search to m7i.large.search

In addition, the default value for the dedicated_master_node of Opensearch clusters has been changed from m4.large.search to m5.large search. The reason for this is that the m5 version is available in all regions, at a consistently cheaper price than the m4 one.

2024-12-17 17:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/camunda/camunda-tf-eks-module?pullRequest=197) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/camunda/camunda-tf-eks-module?pullRequest=197) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/camunda/camunda-tf-eks-module?pullRequest=197) it.</sub>

2024-12-18 08:43 UTC, Langleu requested changes
Overall, looks good 👍.
Just need to install pre-commit locally and run it again to fix it.

```
pre-commit install
pre-commit run --all-files
```

for future changes in this repository you shouldn't have linting problems anymore.

2024-12-18 08:46 UTC, Langleu requested changes
There are a couple of README mentionings with examples where we could update the instance type as well.

Looking at e.g.
- https://github.com/camunda/camunda-tf-eks-module/blob/infex-461-update-instance-type/README.md?plain=1#L63
- https://github.com/camunda/camunda-tf-eks-module/blob/infex-461-update-instance-type/modules/opensearch/README.md?plain=1#L19

2024-12-18 09:59 UTC, bkenez commented
> There are a couple of README mentionings with examples where we could update the instance type as well.
> 
> Looking at e.g.
> 
> * https://github.com/camunda/camunda-tf-eks-module/blob/infex-461-update-instance-type/README.md?plain=1#L63
> * https://github.com/camunda/camunda-tf-eks-module/blob/infex-461-update-instance-type/modules/opensearch/README.md?plain=1#L19

Fixed them, thanks for the pointing it out!

2024-12-18 10:00 UTC, Langleu approved these changes
🚀

2024-12-18 11:47 UTC, merged